name: Deploy Github Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    env:
      GH_PERSONAL_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: prepare
        run: |
          git config --global init.defaultBranch main
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@bots.github.com"

      - run: pnpm install --frozen-lockfile

      - run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages # deploying branch
